[package]
name = "zingo-proxyd"
version = "0.1.0"
authors = ["zingo@zingolabs.org"]
edition = "2021"

[[bin]]
name = "zingoproxyd"
path = "src/bin/zingoproxyd.rs"

[lib]
name = "zingoproxylib"
path = "src/lib.rs"

[features]
# TODO: Add [default = [ "nym" ]] when nym poc is removed, or remove "nym" all together.
nym = []
# NOTE: Deprecated
nym_poc = []

[dependencies]
zingo-rpc = { path = "../zingo-rpc" }

zcash_client_backend = { workspace = true, features = ["lightwalletd-tonic"] }
zingo-netutils = { workspace = true }

nym-sdk = { workspace = true }
nym-sphinx-addressing = { workspace = true }
nym-validator-client = { workspace = true }
nym-bin-common = { workspace = true }
nym-sphinx-anonymous-replies = { workspace = true }

http = { workspace = true }
tokio = { workspace = true, features = ["full"] }
tonic = { workspace = true }
prost = { workspace = true }
bytes = { workspace = true }
http-body = { workspace = true }


tokio-socks = "0.5"
ctrlc = "3.2.1"
tower = { version = "0.4" }
hyper-rustls = { version = "0.23", features = ["http2"] }
tokio-rustls = "0.23"
hyper = { version = "0.14", features = ["full"] }
webpki-roots = "0.21.0"
rustls-pemfile = "1.0.0"

