[package]
name = "integration-tests"
version = "0.1.0"
authors = ["zingo@zingolabs.org"]
edition = "2021"


[features]
nym = []
# NOTE: Deprecated
nym_poc = []

[dependencies]
zingoproxy-testutils = { path = "../zingoproxy-testutils" }
zingo-proxyd = { path = "../zingo-proxyd" }

zcash_client_backend = { workspace = true }
zingo-netutils = { workspace = true }

tokio = { workspace = true }
http = { workspace = true }

# TODO: Change dependency to stable once net-utils merges.
zingolib = { git = "https://github.com/zingolabs/zingolib.git", branch = "nym_integration", features = ["test-features"] }
# zingo-testutils-git = { git = "https://github.com/zingolabs/zingolib.git", branch = "nym_integration" }
zingoconfig = { git = "https://github.com/zingolabs/zingolib.git", branch = "nym_integration" }

zcash_primitives = { git = "https://github.com/zingolabs/librustzcash.git", branch = "nym_integration" }
zcash_address = { git = "https://github.com/zingolabs/librustzcash.git", branch = "nym_integration" }
orchard = "0.8"
shardtree = "0.3"

json = "0.12.4"
log = "0.4.17"
itertools = "0.10.5"
serde_json = "1.0.107"
hex = "0.4"
